# Generated by Django 3.2.8 on 2021-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time created'),
        ),
    ]
