# Generated by Django 3.2.8 on 2021-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_complaint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[('Solved', 'Solved'), ('InProgress', 'InProgress'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
