# Generated by Django 3.2.8 on 2021-10-28 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers:Up to 10 digits allowed.', regex='^\\d{10,10}$')]),
        ),
    ]
