# Generated by Django 3.2.8 on 2021-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering (CSE)'), ('ME', 'Mechanical Engineering (ME)'), ('ECE', 'Electronics & Communication (ECE)'), ('EEE', 'Electrical & Electronics (EEE'), ('SF', 'Fire & Safety (SE)'), ('IT', 'Information Technology (IT)')], default='Computer Science & Engineering (CSE)', max_length=4),
        ),
    ]
